//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Carts = new HashSet<Cart>();
        }
    
        public string UserName { get; set; }
        public string Name { get; set; }
        public string Middle_Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> Phone_Number { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
    }
}
