//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.CartItems = new HashSet<CartItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public string image { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual ICollection<CartItem> CartItems { get; set; }
        public virtual Category Category { get; set; }
    }
}
